// Package domain contains the core business entities of the fleet monitoring system.
//
// WHY a separate domain package: In Clean Architecture, the domain layer
// is the HEART of the application. It defines WHAT the business cares about
// (entities) and WHAT it can do (interfaces), without depending on ANY
// external technology. No database driver, no HTTP framework, no JWT library.
// This makes the business logic testable in isolation and portable to
// different infrastructure (swap SQLite for PostgreSQL without touching
// domain code).
//
// Rule: domain/ NEVER imports from infrastructure/ or application/.
// The dependency direction is always: infrastructure → application → domain.
package domain

import (
	"encoding/json"
	"time"
)

// User represents an authenticated user of the fleet monitoring system.
// There are two roles: "admin" (full access, sees raw device IDs and alerts)
// and "user" (masked device IDs, no alerts).
//
// WHY separate from HTTP request/response: This is the DOMAIN model —
// it represents the business truth. HTTP handlers will map between
// request/response DTOs and this struct.
type User struct {
	// ID is a UUID generated in Go code (using crypto/rand).
	// We don't use auto-increment integers because UUIDs can be
	// generated without database coordination and don't leak record counts.
	ID        string
	Email     string
	Password  string    // bcrypt hash, never plaintext
	Role      string    // "admin" or "user" — enforced by CHECK constraint in SQL
	CreatedAt time.Time
}

// Vehicle represents a physical vehicle in the fleet that has an IoT device attached.
//
// DeviceID is the hardware identifier on the IoT device. This is the field
// that gets MASKED for non-admin users: "DEV-12345678-ABCD" → "DEV-****-ABCD".
// Masking happens at the HTTP handler layer, NOT in the domain or database layer.
type Vehicle struct {
	ID        string
	DeviceID  string    // raw device ID, always stored unmasked in DB
	Name      string    // human-readable name, e.g. "Truck 01"
	CreatedAt time.Time
}

// SensorData represents a single reading from a vehicle's IoT device.
// Each reading has a type (gps, fuel, temperature) and a JSON value payload.
//
// WHY Value as json.RawMessage instead of a Go struct: Different sensor
// types have different value shapes (GPS has lat/lng, fuel has level/unit,
// temperature has celsius). Using json.RawMessage lets us store the raw
// JSON and validate it per-type in the application layer, rather than
// trying to define a single struct that fits all types.
type SensorData struct {
	ID         string
	VehicleID  string
	Type       string           // "gps", "fuel", or "temperature"
	Value      json.RawMessage   // type-specific JSON payload
	Timestamp  time.Time         // when the device recorded this reading
	CreatedAt  time.Time         // when the server stored it
}

// SensorInput is the shape of incoming sensor data from the API request.
// It's separate from SensorData because API input needs validation
// before it becomes a domain entity.
type SensorInput struct {
	DeviceID  string           `json:"device_id"`
	Timestamp string           `json:"timestamp"` // ISO 8601 string — parsed to time.Time
	Type      string           `json:"type"`
	Value     json.RawMessage  `json:"value"`
}

// Alert represents a predictive alert generated by the system.
// Currently only "low_fuel" alerts exist, but the type field allows
// for future alert types (overheating, disconnected device, etc.).
//
// WHY separate from SensorData: Alerts are NOT sensor readings — they're
// BUSINESS DERIVATIONS. A fuel reading doesn't become an alert until the
// calculation engine determines autonomy < 1 hour. Storing them separately
// lets us query alerts independently and apply role-based visibility.
type Alert struct {
	ID        string
	VehicleID string
	Type      string            // e.g., "low_fuel"
	Severity  string            // e.g., "critical"
	Details   json.RawMessage   // calculation results (autonomy, rate, etc.)
	CreatedAt time.Time
}

// GPSCoordinates represents the value payload for a GPS sensor reading.
// Used for validation and type-safe access in the application layer.
type GPSCoordinates struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// FuelReading represents the value payload for a fuel sensor reading.
// The Level field is in liters, Unit is always "liters" per spec.
type FuelReading struct {
	Level float64 `json:"level"`
	Unit  string  `json:"unit"`
}

// TemperatureReading represents the value payload for a temperature sensor.
type TemperatureReading struct {
	Celsius float64 `json:"celsius"`
}

// FuelReadingWithTime combines a fuel level with its timestamp.
// This is used by the fuel calculation service to compute consumption rates.
// It's an application-layer construct, not stored directly in the DB.
type FuelReadingWithTime struct {
	Level     float64
	Timestamp time.Time
}

// Claims represents the data stored inside a JWT payload.
// These are the "claims" (assertions) about the authenticated user.
//
// WHY in domain (not jwt package): Claims are a domain concept — they
// represent user identity and role. The jwt package handles encoding/decoding,
// but the definition of WHAT a claim IS belongs to the domain. This way,
// the application layer can reference Claims without depending on the jwt package.
//
// WHY these specific fields:
//   - sub (subject): the user's unique ID — used to identify WHO this token belongs to
//   - email: included so the frontend can display it without a DB query
//   - role: included so RBAC middleware can check permissions without a DB query
//   - iat (issued at): when the token was created — useful for debugging
//   - exp (expires at): when the token becomes invalid — critical for security
//   - Type: "access" or "refresh" — distinguishes access tokens from refresh tokens
type Claims struct {
	Subject  string `json:"sub"`   // user ID
	Email    string `json:"email"` // user email
	Role     string `json:"role"`  // "admin" or "user"
	IssuedAt int64  `json:"iat"`   // Unix timestamp of token creation
	ExpireAt int64  `json:"exp"`   // Unix timestamp of token expiration
	Type     string `json:"type"`  // "access" or "refresh"
}